version: "3.8"
services:
  db_movies:
    container_name: db_movies
    image: postgres:latest
    environment:
      POSTGRES_DB: 'movies'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5432:5432'
    restart: always
