version: "3.8"
services:
  db_movies:
    container_name: db_movies
    image: postgres:latest
    environment:
      POSTGRES_DB: 'movies'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5432:5432'
    restart: always
  db_series:
    container_name: db_series
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: 'series'
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'password'
    ports:
      - '27018:27017'
    restart: always
    volumes:
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  zipkin_server:
    depends_on:
      - storage-aux-container
    container_name: zipkin_server
    image: openzipkin/zipkin-slim
    environment:
      - STORAGE_TYPE=mem
    ports:
      - '9411:9411'
    restart: always
 