server:
  port: ${PORT:8888}

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sergierog/Parcial1_EspBack1_RB_SR.git
          search-paths: config-data
          force-pull: true